export const links = [
  {
    title: "How it works",
    url: "/#how-it-works",
  },
  {
    title: "Events",
    url: "/events",
  },
  {
    title: "Shop",
    url: "/shop",
  },
  {
    title: "Articles",
    url: "/articles",
  },
];

export const shopProducts = [
  {
    id: 1,
    name: "Reusable Water Bottle",
    price: 500,
    category: "Eco-Friendly Products",
    location: "New York, USA",
    wasteMaterial: ["Recycled Aluminum"],
    company: {
      name: "EcoHydrate",
      location: "Portland, USA",
    },
    availability: 25,
    totalStock: 100,
    path: "/shop/reusable-water-bottle",
  },
  {
    id: 2,
    name: "Organic Cotton Tote Bag",
    price: 300,
    category: "Eco-Friendly Products",
    location: "Los Angeles, USA",
    wasteMaterial: ["Organic Cotton Scraps"],
    company: {
      name: "GreenBags Co.",
      location: "San Francisco, USA",
    },
    availability: 40,
    totalStock: 200,
    path: "/shop/organic-cotton-tote-bag",
  },
  {
    id: 3,
    name: "Recycling Bin Set",
    price: 1500,
    category: "Home & Garden",
    location: "Toronto, Canada",
    wasteMaterial: ["Recycled Plastic"],
    company: {
      name: "ReCycleWorks",
      location: "Toronto, Canada",
    },
    availability: 15,
    totalStock: 50,
    path: "/shop/recycling-bin-set",
  },
  {
    id: 4,
    name: "Solar Powered Charger",
    price: 2500,
    category: "Electronics",
    location: "San Francisco, USA",
    wasteMaterial: ["Recycled Electronic Components"],
    company: {
      name: "SunTech",
      location: "San Francisco, USA",
    },
    availability: 10,
    totalStock: 30,
    path: "/shop/solar-powered-charger",
  },
  {
    id: 5,
    name: "Bamboo Toothbrush Pack",
    price: 200,
    category: "Personal Care",
    location: "Vancouver, Canada",
    wasteMaterial: ["Sustainable Bamboo"],
    company: {
      name: "EcoBrush",
      location: "Vancouver, Canada",
    },
    availability: 50,
    totalStock: 150,
    path: "/shop/bamboo-toothbrush-pack",
  },
  {
    id: 6,
    name: "Compostable Phone Case",
    price: 800,
    category: "Accessories",
    location: "London, UK",
    wasteMaterial: ["Plant-Based Materials"],
    company: {
      name: "GreenCase",
      location: "London, UK",
    },
    availability: 20,
    totalStock: 100,
    path: "/shop/compostable-phone-case",
  },
  {
    id: 7,
    name: "Eco-Friendly Cleaning Kit",
    price: 1200,
    category: "Home & Garden",
    location: "Sydney, Australia",
    wasteMaterial: ["Recycled Plastic Bottles"],
    company: {
      name: "CleanGreen",
      location: "Melbourne, Australia",
    },
    availability: 30,
    totalStock: 120,
    path: "/shop/eco-friendly-cleaning-kit",
  },
  {
    id: 8,
    name: "LED Light Bulb Pack",
    price: 600,
    category: "Electronics",
    location: "Berlin, Germany",
    wasteMaterial: ["Recycled Glass", "Recycled Metal"],
    company: {
      name: "BrightFuture",
      location: "Berlin, Germany",
    },
    availability: 60,
    totalStock: 200,
    path: "/shop/led-light-bulb-pack",
  },
  {
    id: 9,
    name: "Recycled Notebook",
    price: 150,
    category: "Stationery",
    location: "Paris, France",
    wasteMaterial: ["Recycled Paper"],
    company: {
      name: "PaperCycle",
      location: "Paris, France",
    },
    availability: 100,
    totalStock: 500,
    path: "/shop/recycled-notebook",
  },
  {
    id: 10,
    name: "Stainless Steel Straw Set",
    price: 350,
    category: "Eco-Friendly Products",
    location: "Amsterdam, Netherlands",
    wasteMaterial: ["Recycled Stainless Steel"],
    company: {
      name: "EcoStraw",
      location: "Rotterdam, Netherlands",
    },
    availability: 75,
    totalStock: 300,
    path: "/shop/stainless-steel-straw-set",
  },
];
